Todo components
ValeryRul/notes pull request #11
Opened 2021-12-01 23:08 UTC by ValeryRul

https://trello.com/c/rRnYVZjY/7-%D0%B3%D0%BB%D0%B0%D0%B2%D0%BD%D0%B0%D1%8F-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0

2021-12-02 16:36 UTC, Zwezh requested changes

2021-12-02 16:36 UTC, Zwezh commented on src/app/modules/main/main-page/main-page.component.scss
> +}
Это должно быть внутри todo-container а не снаружи

2021-12-02 16:36 UTC, Zwezh commented on src/app/modules/todo/components/add-todo/add-todo.component.html
> +  </div>
Неиспользуемые кнопки должны быть скрыты пример через ngif false или display none

2021-12-02 16:36 UTC, Zwezh commented on src/app/modules/todo/components/todo-component/todo.component.html
> +  </div>
Неиспользуемые кнопки должны быть скрыты пример через ngif false или display none

2021-12-02 16:36 UTC, Zwezh commented on src/app/modules/todo/components/todo-component/todo.component.html
> +  <input class="form-control w-100" type="text" value="{{ todo.title }}"/>
почему не [value]="todo.title"?

2021-12-02 16:36 UTC, Zwezh commented on src/app/modules/todo/components/todo-component/todo.component.ts
> +    return noteText.trim();
зачем принимать целую туду когда можно принять просто notes?

2021-12-07 14:44 UTC, Zwezh requested changes

2021-12-07 14:44 UTC, Zwezh commented on src/app/modules/todo/components/add-todo/add-todo.component.ts
> +    color: '',
Должно быть единообразие в проекте либо одинарные либо двойные кавычки, лучше одинарные.

2021-12-07 14:44 UTC, Zwezh commented on src/app/modules/todo/components/add-todo/add-todo.component.ts
> +  note: Todo = {
Выглядит так как будто это приватное поле

2021-12-07 14:44 UTC, Zwezh commented on src/app/modules/todo/components/add-todo/add-todo.component.ts
> +  }
Этот метод нигде не используется

2021-12-07 14:44 UTC, Zwezh commented on src/app/modules/todo/components/add-todo/add-todo.component.ts
> +  }
Нужен пустой конструктор?

2021-12-07 14:44 UTC, Zwezh commented on src/app/modules/todo/components/add-todo/add-todo.component.ts
> +  convertTextToNoteArr(){
Возвращаемого значения почему-то нету

2021-12-07 14:44 UTC, Zwezh commented on src/app/modules/todo/components/add-todo/add-todo.component.ts
> +  onCreateTodo(){
Возвращаемого значения почему-то нету

2021-12-07 14:44 UTC, Zwezh commented on src/app/modules/todo/components/add-todo/add-todo.component.ts
> +    console.log(this.noteText, this.noteTitle)
Непонятно если честно для чего нужна такая конструкция для if всегда должны быть фигурные скобки

2021-12-07 14:44 UTC, Zwezh commented on src/app/modules/todo/components/add-todo/add-todo.component.scss
>  @import 'src/assets/styles/_colors.scss';
Достаточно просто @import 'src/assets/styles/colors';

2021-12-07 14:44 UTC, Zwezh commented on src/app/modules/todo/components/todo-container/todo-container.component.html
> +  </ng-container>
В ng-container обарачивать в данном случае не нужно

2021-12-07 14:44 UTC, Zwezh commented on src/app/modules/todo/todo.module.ts
> +  exports: [TodoComponent, AddTodoComponent, TodoContainerComponent]
На экспорт по сути нужен только 1 компонент

2021-12-07 21:32 UTC, ValeryRul commented on src/app/modules/todo/components/add-todo/add-todo.component.ts
> +    console.log(this.noteText, this.noteTitle)
это не должно было попасть в коммит. случайно

2021-12-08 09:20 UTC, merged